<?php echo $this->partial('layout/header.phtml'); ?>

<h1></h1>

<a class="btn btn-primary" href="<?php echo $this->url($route); ?>"">Regresar</a>

<?php
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
?>
<h3>General</h3>
<table class="table table-striped table-bordered model-list">
    <tbody>
    <?php
        $e=$form->get('csrf_token');
        echo $this->formInput($e);
        $e=$form->get('id');
        echo $this->formHidden($e);
        foreach ($this->form as $element) {
            $attributes=$element->getAttributes();
            $label = $element->getLabel();
            $type=$attributes['type'];
            if($label!='') {
                echo "<tr>";
                echo "<td>";
                echo $label;
                echo "</td>";
                echo "<td>";
                switch($type){
                    case 'text':
                        echo $this->FormInput($element);
                        break;
                    case 'select':
                        echo $this->FormSelect($element);
                        break;
                    case 'multi_checkbox':
                        echo $this->FormMultiCheckbox($element);
                        break;
                    case 'email':
                        echo $this->FormEmail($element);
                        break;
                    case 'password':
                        echo $this->FormPassword($element);
                        break;
                    case 'checkbox':
                        echo $this->FormCheckbox($element);
                        break;
                    case 'textarea':
                        echo $this->formTextArea($element);
                        break;
                    case 'datetime':
                        echo $this->FormDatetime($element);
                        break;
                    case 'file':
                        echo $this->formFile($element);
                        break;
                }
                echo $this->formElementErrors()->render($element);
                echo "</td>";
                echo "</tr>";
            }
        }
    ?>
    </tbody>
</table>

<?php
$e = $form->get('form-btn');
echo $this->FormSubmit($e);
echo $this->form()->closeTag();
?>

<?php echo $this->partial('layout/footer.phtml'); ?>

