<?php if(in_array('policy-view',$perms)){ ?>
<li>
    <a class="list-group-item" data-toggle="collapse" href="#nav-policy">Policy 
        <b class="caret"></b>
    </a>
    <ul class="collapse" id="nav-policy">
        <?php if(in_array('policy-view',$perms)){?>
        <li>
            <a class="list-group-item" href="
                <?php echo $this->url('admin/policy') ?>">Términos
            </a>
        </li>
        <?php }?>
    </ul>
</li>
<?php } ?>