<?php echo $this->partial('admin/layout/header.phtml'); 
if(isset($plugings) && !is_null($plugings)){
    if(in_array('fancybox', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/fancybox/jquery.fancybox.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/fancybox/jquery.fancybox.pack.js');    
    }
    if(in_array('colorpicker', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/bootstrap-colorpicker/css/bootstrap-colorpicker.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-colorpicker/js/bootstrap-colorpicker.js');    
    }
    if(in_array('datepicker',$plugings)){
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-datepicker.js');
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/css/datepicker.css');
    }
}
?>

<h1>Roles</h1>
<?php
if(isset($errors) && count($errors)>0){
    ?>
    <div class="alert alert-danger alert-error">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>Error!</strong> Se encontraron errores o campos que no se han llenado
    </div>
    <?php
}
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
$e=$form->get('csrf_token');
echo $this->formInput($e);
?>
    <table class="table table-striped table-bordered model-list">
    <tbody>
    <?php
    foreach ($form as $element) {
        $attributes=$element->getAttributes();
    }
    ?>
    </tbody>
    </table>


<table class="table table-striped table-bordered model-list">
<tbody>

    <tr>
        <td><?php echo $this->formLabel($form->get('name')); ?></td>
        <td>
            <?php 
                echo $this->formElement($form->get('name')); 
                echo $this->formElementErrors($form->get('name'));
            ?>
        </td>
    </tr>



    <tr>
        <td><?php echo $this->formLabel($form->get('permissions')); ?></td>
        <td>
            <?php 
                echo $this->formElement($form->get('permissions')); 
                echo $this->formElementErrors($form->get('permissions'));
            ?>
        </td>
    </tr>


</tbody>
</table>


<table class="table table-striped table-bordered model-list">
<tbody>
    <tr>
        <td><?php  echo $this->formElement($form->get('submit')); ?></td>
    </tr>
</tbody>
</table>

<?php echo $this->form()->closeTag(); ?>
<?php echo $this->partial('admin/layout/footer.phtml');?>

<script>
    CKEDITOR.replace('content', {
        toolbar: [
            {name: 'document', items: ['Source']},
            {name: 'clipboard', items: ['Paste', 'PasteText', 'PasteFromWord']},
            {name: 'basicstyles', items: ['Bold', 'Italic', '-', 'NumberedList', 'BulletedList']},
            {name: 'links', items: ['Link']},
            {name: 'insert', items: ['Image', 'SpecialChar']}
        ]
    });

$('.btn_event_photo_add').on('click', function(e){
    e.preventDefault();
    var row = $('#files tr:last').clone(true);
    $('#files').append(row);
    return true;
});

$('.btn_event_photo_delete').on('click', function(e){
    e.preventDefault();
    var $this = $(this);
    var div = $this.parent().parent();
    div.remove();
    return false;
});
</script>
