<?php 
echo $this->partial('admin/layout/header.phtml'); 

$title = 'Roles';
$this->headTitle($title); 
$route = 'admin/system_roles';
?>

<h1><?php echo $this->escapeHtml(ucfirst($title)); ?></h1>

<?php if ($msg != '') { ?>
<div class="alert alert-success"><?php echo $msg;?></div>
<?php } ?>



<p><a class="btn btn-success" href="<?php echo $this->url($route.'/get/add');?>"><i class="glyphicon glyphicon-plus"></i>Add new</a></p>


<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-condensed">
        <tr>
            <td>title</td>
            <td>status</td>
            <td>created_at</td>
            <td></td>
            <td></td>    
        </tr>

        <?php foreach ($paginator as $row) { ?>
        <tr>
            <td><?php echo $row->name ?></td>
            <td><?php echo $row->status ?></td>
            <td><?php echo $row->created_at ?></td>
            <td>
                <a class="btn btn-default btn-xs" href="<?php echo $this->url($route.'/get/edit', array('id' => $row->id));?>"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            </td>        
            <td>
                <a class="btn btn-default btn-xs" data-modal="#modal-confirm" data-target="<?php echo $this->url($route.'/get/delete', array('action' => 'delete','id' => $row->id));?>">
                    <i class="glyphicon glyphicon-remove"></i>Delete
                </a>
            </td>
                      

         </tr>
         <?php } ?>

    </table>
</div>

 <script src="<?php echo $this->basePath() . '/cms/js/bootstrap-confirm.js'; ?>"></script>
<?php echo $this->paginationControl($this->paginator,'sliding', array('admin/layout/slidePaginator.phtml','Users'), array('route' => $route)); ?>
<?php echo $this->partial('admin/layout/footer.phtml');?>