
<?php echo $this->partial('admin/layout/header.phtml'); 
if(isset($plugings) && !is_null($plugings)){
    if(in_array('fancybox', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/fancybox/jquery.fancybox.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/fancybox/jquery.fancybox.pack.js');    
    }
    if(in_array('colorpicker', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/bootstrap-colorpicker/css/bootstrap-colorpicker.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-colorpicker/js/bootstrap-colorpicker.js');    
    }
    if(in_array('datepicker',$plugings)){
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-datepicker.js');
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/css/datepicker.css');
    }
}

$title = explode("/", $route);
    if(isset($url)){
        ?>
        <div id="url" data-url=<?php echo $url; ?>></div>
                <script src="
            <?php echo $this->basePath() . '/cms/js/section.js'; ?>">
        </script>
        <?php
    }
?>

<a class="btn btn-primary" href="<?php echo $this->url($route); ?>">Regresar</a>
<h1><?php echo ucfirst($title[1]); ?></h1>
<?php
if(isset($errors) && count($errors)>0){
    ?>
    <div class="alert alert-danger alert-error">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>Error!</strong> Se encontraron errores o campos que no se han llenado
    </div>
    <?php
}
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
$e=$form->get('csrf_token');
echo $this->formInput($e);
$e=$form->get('id');
echo $this->formHidden($e);
if(isset($tabs) && !is_null($tabs)){
    $keys = array_keys($tabs);
    ?>
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <?php
        $index = 0;
        $active= '';
        foreach ($keys as $tab) {
            $active = $index == 0 ? 'active' : '';
            $index++;
            ?>
            <li class="<?php echo $active; ?>"><a href="#<?php echo $tab; ?>" data-toggle="tab"><?php echo $tab; ?></a></li>
        <?php
        }
        ?>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php
        $index = 0;
        $active= '';
        foreach ($tabs as $key=>$tab) {
            $active = $index == 0 ? 'active' : '';
            $index++;
            ?>
            <div class="tab-pane <?php echo $active; ?>" id="<?php echo $key ?>">
                <table class="table table-striped table-bordered model-list">
                    <tbody>
                    <?php
                    foreach ($tab as $t) {
                        $element = $form->get($t);
                        $vars = array("element"=>$element,'files'=>$files);
                        if(isset($object->file_path)){
                            $vars['object'] = $object->file_path;
                        }
                        echo $this->partial('admin/base/templates/printForm_old.phtml',$vars);
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        <?php
        }
        ?>
    </div>
<?php
}else{
    ?>
    <table class="table table-striped table-bordered model-list">
    <tbody>
    <?php
    foreach ($form as $element) {
        $attributes=$element->getAttributes();
        if(isset($files)){
            $vars = array("element"=>$element,'files'=>$files);    
        }else{
            $vars = array("element"=>$element);
        }
        
        if(isset($object->file_path)){
            $vars['object'] = $object->file_path;
        }
        echo $this->partial('admin/base/templates/printForm_old.phtml',$vars);
    }
    ?>
    </tbody></table>
<?php
}

$e = $form->get('form-btn');
echo $this->FormSubmit($e);
echo $this->form()->closeTag();
?>
<?php echo $this->partial('admin/layout/footer.phtml');?>
