
<?php echo $this->partial('admin/layout/header.phtml'); 
if(isset($plugings) && !is_null($plugings)){
    if(in_array('fancybox', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/fancybox/jquery.fancybox.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/fancybox/jquery.fancybox.pack.js');    
    }
    if(in_array('colorpicker', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/bootstrap-colorpicker/css/bootstrap-colorpicker.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-colorpicker/js/bootstrap-colorpicker.js');    
    }
    if(in_array('datepicker',$plugings)){
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-datepicker.js');
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/css/datepicker.css');
    }
}

$title = explode("/", $route);
    if(isset($url)){
        ?>
        <div id="url" data-url=<?php echo $url; ?>></div>
                <script src="
            <?php echo $this->basePath() . '/cms/js/section.js'; ?>">
        </script>
        <?php
    }
?>
<?php if(isset($hasUbigeo) && !is_null($hasUbigeo)){ ?>
<script>

$(document).ready(init);
  var $form;
  function init () {
    var dpt   = $('#departamento'),
        prov  = $('#provincia'),
        dist  = $('#distrito');
   
    $form = $('.form-horizontal');
    dpt.on('change', loadProv);
    prov.on('change', loadDist);
  }

  function loadProv() {
    var $this = $(this),
        selectedVal = $this.val(),
        $el = $('#provincia'),
        $sub_el = $('#distrito'),
        html = '<option value="">Selecciona</option>',
        item;

    if (selectedVal === '') {
      $el.html(html)
        .attr('disabled')
    } else  {

      $el.html(html);
      $el.removeAttr('disabled');
      $el.trigger('change');
      $sub_el.html(html).attr('disabled','disabled');
      $sub_el.trigger('change');
      $.post($form.attr('data-provinces'), {
        'department' : selectedVal
      }).done( function(data) {
        for (item in data) {
          html += '<option value="' + data[item].id + '">' + data[item].name + '</option>';
        }
        $el.html(html);
      });  
    }
  };

  function loadDist() {
    var $el = $('#distrito'),
        $dept = $('#departamento'),
        $this = $(this),
        html = '<option value="">Selecciona</option>',
        selectedVal = $this.val(),
        item;

    if (selectedVal === '') {
      $el.html(html);
      $el.attr('disabled','disabled');
      $el.parent().addClass('ci-select-disabled');
      $el.trigger('change');
    } else {
      $el.removeAttr('disabled');
      $el.parent().removeClass('ci-select-disabled');
      $el.trigger('change');
      $.post($form.attr('data-districts'), {
        'department' : $dept.val(),
        'province' : $this.val(),
      }).done(function (data) {
        for (item in data) {
          html += '<option value="' + data[item].id + '">' + data[item].name + '</option>';
        }
        $el.html(html);
      });
    }
  };

</script>
<?php } ?>

<h1 class="titleSection titleSection--add"><?php echo ucfirst($title[1]); ?></h1>
<a class="btn btn-primary btn-sm backBtn backBtn--add" href="<?php echo $this->url($route); ?>">
    <i class="fa fa-long-arrow-left"></i>
    Regresar
</a>
<div class="contentInner">
<?php
if(isset($errors) && count($errors)>0){
    ?>
    <div class="alert alert-danger alert-error">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>Error!</strong> Se encontraron errores o campos que no se han llenado
    </div>
    <?php
}
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true));
$form->setAttribute('class', 'form-horizontal');
if(isset($hasUbigeo) && !is_null($hasUbigeo)){ 
$form->setAttribute('data-provinces', $this->url('provinces',array(), array('force_canonical' => true)));
$form->setAttribute('data-districts', $this->url('districts',array(), array('force_canonical' => true)));
}
$form->prepare();
echo $this->form()->openTag($form);
$e=$form->get('csrf_token');
echo $this->formInput($e);
$e=$form->get('id');
echo $this->formHidden($e);
if(isset($tabs) && !is_null($tabs)){
    $keys = array_keys($tabs);
    ?>
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <?php
        $index = 0;
        $active= '';
        foreach ($keys as $tab) {
            $active = $index == 0 ? 'active' : '';
            $index++;
            ?>
            <li class="<?php echo $active; ?>"><a href="#<?php echo $tab; ?>" data-toggle="tab"><?php echo $tab; ?></a></li>
        <?php
        }
        ?>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php
        $index = 0;
        $active= '';
        foreach ($tabs as $key=>$tab) {
            $active = $index == 0 ? 'active' : '';
            $index++;
            ?>
            <div class="tab-pane <?php echo $active; ?>" id="<?php echo $key ?>">
                <table class="table table-striped table-bordered model-list">
                    <tbody>
                    <?php
                    foreach ($tab as $t) {
                        $element = $form->get($t);
                        $vars = array("element"=>$element,'files'=>$files);
                        if(isset($object->file_path)){
                            $vars['object'] = $object->file_path;
                        }
                        echo $this->partial('admin/base/templates/printForm.phtml',$vars);
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        <?php
        }
        ?>
    </div>
<?php
}else{
    ?>

    <?php
    foreach ($form as $element) {
        $attributes=$element->getAttributes();
        if(isset($files)){
            $vars = array("element"=>$element,'files'=>$files);    
        }else{
            $vars = array("element"=>$element);
        }
        
        if(isset($object->file_path)){
            $vars['object'] = $object->file_path;
        }
        echo $this->partial('admin/base/templates/printForm.phtml',$vars);
    }
    ?>

<?php
}
?>
                      <br>
                      <div class="row">
                        <div class="col-sm-2">
                          &nbsp;
                        </div>
                        <div class="col-sm-10">
<?php

$e = $form->get('form-btn');
echo $this->FormButton()->openTag($e);
echo '<i class="glyphicon glyphicon-floppy-disk"></i> Grabar';
echo $this->FormButton()->closeTag();
?>
                        </div>
                      </div>
<?php


echo $this->form()->closeTag();
?>
</div>
<?php echo $this->partial('admin/layout/footer.phtml');?>
