<a class="btn btn-xs btn-info" href="
    <?= $this->url($route . '/view', array('id' => $record->id));?>?page=<?= $page ?>">
    <i class="glyphicon glyphicon-eye-open"></i> View
</a>

<?php if(in_array(sprintf("%s-edit", $perm), $perms)) { ?>
<a class="btn btn-xs btn-warning" href="
    <?= $this->url($route . '/update', array('id' => $record->id));?>?page=<?= $page ?>">
    <i class="glyphicon glyphicon-pencil"></i> Edit
</a>
<?php } ?>

<?php if(in_array(sprintf("%s-delete", $perm), $perms)) { ?>
<a class="btn btn-xs btn-danger" data-modal="#modal-confirm" data-target="
    <?= $this->url($route . '/delete', array('action' => 'delete', 'id' => $record->id));?>?page=<?= $page ?>">
    <i class="glyphicon glyphicon-remove"></i> Delete
</a>
<?php } ?>

