<?php
echo $this->partial('admin/layout/header.phtml');
$title = explode("/", $route);
$perm = str_replace('_', '-', $title[1]);
$title = str_replace("_", " ", $title[1]);
$this->headTitle($title);
$add = in_array(sprintf("%s-add", $perm), $perms) ? true : false;
$delete = in_array(sprintf("%s-delete", $perm), $perms) ? true : false;
$edit = in_array(sprintf("%s-edit", $perm), $perms) ? true : false;
$delete_url  = sprintf('%s/delete/get', $route);
$route = sprintf('%s/view/get', $route);

if (isset($display_fields)) {
	$keys = $display_fields;
} else {
	$keys = array_keys(get_object_vars($paginator->getCurrentItems()->getArrayObjectPrototype())); sort($keys);
} ?>
<h1 class="titleSection">
    <?php echo $this->escapeHtml(ucfirst($title)); ?>
</h1>
<div class="contentInner">
<?php if ($msg != '') { ?>
<div class="alert alert-success">
    <?php echo $msg;?>
</div>
<?php } ?>
<?php if ($add) { ?>
<p class="m-b-20 clearfix">
    <a class="btn btn-success newBtn" href="
        <?php echo $this->url($route);?>">
        <i class="glyphicon glyphicon-plus"></i>  Agregar
    </a>
</p>
<?php } ?>

<div class="table-responsive">
<?php
if(isset($this->form)){
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
?>
 <table class="table table-striped table-bordered model-list">
        <tbody>
        <tr>
        <?php
            if($form->has('csrf_token')){
                $e=$form->get('csrf_token');
                echo $this->formInput($e);
            }
            foreach ($form as $element) {
            $attributes=$element->getAttributes();
            $label = $element->getLabel();
            $type=$attributes['type'];
            $name=$attributes['name'];
            echo "<td>";
            if($label!=''){
                //echo "<td>";
                echo $label;
                echo "<br>";
                //echo "</td>";
            }
            if($type!='hidden'){
                //echo "<td>";
                switch($type){
                case 'text':
                    echo $this->FormInput($element);
                    break;
                case 'select':
                    echo $this->FormSelect($element);
                    break;
                case 'multi_checkbox':
                    echo $this->FormMultiCheckbox($element);
                    break;
                case 'email':
                    echo $this->FormEmail($element);
                    break;
                case 'password':
                    echo $this->FormPassword($element);
                    break;
                case 'checkbox':
                    echo $this->FormCheckbox($element);
                    break;
                case 'textarea':
                    echo $this->formTextArea($element);
                    break;
                case 'submit':
                    echo $this->formSubmit($element);
                    break;
                }
                //echo "</td>";
            }
            echo "</td>";

        } ?>
        </tr>

        </tbody>
    </table>
    <p>Resultados <?php echo $paginator->getTotalItemCount() ?></p>
    <?php } ?>
    <table class="table table-striped table-hover table-condensed">
        <tr>
            <?php foreach ($keys as $key) { ?>
            <td>
                <?php echo ucfirst($key);?>
            </td>
            <?php } ?>
            <td>

            </td>
        </tr>
        <?php foreach ($paginator as $page) { ?>
	        <tr>
			<?php
        		foreach ($keys as $key) {
	        		echo "<td>" . $page->{$key} . '</td>';
	        	}
	        ?>
            <td>
                <?php if ($edit) { ?>
                <a class="btn btn-xs btn-warning" href="
                    <?php echo $this->url($route, array('id' => $page->id));?>">
                    <i class="glyphicon glyphicon-pencil"></i> Edit
                </a>
                <?php } ?>
                <?php if ($delete) {?>
                <a class="btn btn-xs btn-danger" data-modal="#modal-confirm" data-target="

                    <?php echo $this->url($delete_url, array('action' => 'delete','id' => $page->id));?>">
                    <i class="glyphicon glyphicon-remove"></i>Delete
                </a>
                <?php } ?>
            </td>
            </tr>
            <?php } ?>
        </table>
        <script src="
            <?php echo $this->basePath() . '/cms/js/bootstrap-confirm.js'; ?>">
        </script>
        <?php $route = explode('/', $route); $route = $route[0].'/'.$route[1];
        $array = array('route'=>$route);
        if(isset($params)){
            $array['params'] = $params;
        }
        echo $this->paginationControl($this->paginator, 'sliding',
                array('admin/layout/slidePaginator.phtml','Users'), $array ); ?>
    </div>
    </div>
    <?php echo $this->partial('admin/layout/footer.phtml');?>