<?php 
$element = $flr->elements[$name];

$label = (isset($element['label']) ? $element['label'] : $name);

echo "<tr><td>";
echo $label;
echo "</td><td>";

switch($element['type']) {
    case 'Text':
    case 'Number':
        echo $this->FormInput($form_element);
        break;
    
    case 'Select':
        echo $this->FormSelect($form_element);
        break;
    
    case 'MultiCheckbox':
        echo $this->FormMultiCheckbox($form_element);
        break;
    
    case 'Email':
        echo $this->FormEmail($form_element);
        break;
    
    case 'Password':
        echo $this->FormPassword($form_element);
        break;
    
    case 'Checkbox':
        echo $this->FormCheckbox($form_element);
        break;
    
    case 'Textarea':
        echo $this->formTextArea($form_element);
        break;
    
    case 'File':
        if($record->has_file($name)) {
            echo $record->files()->$name->filename . ' ';
            if(isset($element['admin']) && isset($element['admin']['view_as'])) {
                if($element['admin']['view_as'] == 'image') {
                    echo '(<a class="images" href="' . $element['admin']['path'] . $record->files()->$name->filename . '">Show image</a>)';
                }
                else {
                    echo '(<a class="images" href="' . $element['admin']['path'] . $record->files()->$name->filename . '" target="_blank">Download file</a>)';
                }
            }
            else {
                echo $record->files()->$name->filename;
            }
            echo '<br>';
            
            if(isset($element['admin']) && isset($element['admin']['accept_remove']) && $element['admin']['accept_remove'] == true) {
                ?>
                <input type="checkbox" name="_remove_<?= $name ?>" value='1'> Remove file<br>
                <?php
            }
        }
        echo $this->formFile($form_element);
        
        break;
    
    default:
        echo $type;
        break;
}
echo $this->formElementErrors()->render($form_element);
echo "</td>";
echo "</tr>";

?>