<?php 
$element = $flr->elements[$name];
$label      = $form_element->getLabel();

$label = (isset($element['label']) ? $element['label'] : $name);

echo "<tr><td>";
echo $label;
echo "</td><td>";

switch($element['type']) {
    case 'Checkbox':
        if($record->$name == 1) {
        ?>
        <img src="/cms/img/icon-yes.gif">
        <?php
        }
        else {
        ?>
        <img src="/cms/img/icon-no.gif">
        <?php
        }
    case 'File':
        if($record->has_file($name)) {
            $filename = $record->files()->$name->filename;
            $fe       = $flr->elements[$name];
            
            if(isset($fe['admin']) && isset($fe['admin']['view_as']) && $fe['admin']['view_as'] == 'image') {
                echo '<img src="' . $fe['admin']['path'] . $filename . '" style="max-width: 300px; max-height: 300px">';
            }
            else {
                echo $filename;
            }
        }
        break;
    
    default:
        echo $record->$name;
        break;
}
?>
</td></tr>

