<?php 
$element = $flr->elements[$name];

$label = (isset($element['label']) ? $element['label'] : $name);

echo "<tr><td>";
echo $label;
echo "</td><td>";

switch($element['type']) {
    case 'Text':
    case 'Number':
        echo $this->FormInput($form_element);
        break;
    
    case 'Select':
        echo $this->FormSelect($form_element);
        break;
    
    case 'MultiCheckbox':
        echo $this->FormMultiCheckbox($form_element);
        break;
    
    case 'Email':
        echo $this->FormEmail($form_element);
        break;
    
    case 'Password':
        echo $this->FormPassword($form_element);
        break;
    
    case 'Checkbox':
        echo $this->FormCheckbox($form_element);
        break;
    
    case 'Textarea':
        echo $this->formTextArea($form_element);
        break;
    
    case 'File':
        echo $this->formFile($form_element);
        
        if($record->has_file($name)) {
            if(isset($element['admin']) && isset($element['admin']['view_as']) && $element['admin']['view_as'] == 'image') {
                echo '<a class="images" href="' . $element['admin']['path'] . $record->files()->$name->filename . '">Ver Imagen</a>';
            }
        }
        break;
    
    default:
        echo $type;
        break;
}
echo $this->formElementErrors()->render($form_element);
echo "</td>";
echo "</tr>";

?>