<?= $this->partial('admin/layout/header.phtml') ?>

<a class="btn btn-primary" href="<?php echo $this->url($route); ?>?page=<?= $page ?>">Go back</a>

<h1><?php echo $title; ?> - <?= $id ?></h1>

<table class="table table-striped table-bordered model-list">
<tbody>
<?php
foreach($flr->elements as $name => $flr_element) {
    if($name !== 'csrf') {
        $vars = array(
            'flr'          => $flr,
            'form'         => $form,
            'name'         => $name,
            'form_element' => $form->get($name),
            'flr_element'  => $flr_element,
            'record'       => $record,
            'files'        => $files,
        );
        
        if(isset($flr_element['admin']) && isset($flr_element['admin']['view'])) {
            $partial = $flr_element['admin']['view'];
        }
        else {
            $partial = 'admin/base/templates/printViewPlus';
        }
        
        echo $this->partial($partial, $vars);
    }
}
?>
</tbody>
</table>

<?= $this->partial('admin/layout/footer.phtml');?>

