<?php 
echo $this->partial('admin/layout/header.phtml'); 

$title = explode("/", $route); 
$perm = str_replace('_', '-', $title[1]); 
$title = str_replace("_", " ", $title[1]); 
$this->headTitle($title); 

$add = in_array(sprintf("%s-add", $perm), $perms) ? true : false; 
$delete = in_array(sprintf("%s-delete", $perm), $perms) ? true : false;
$edit = in_array(sprintf("%s-edit", $perm), $perms) ? true : false; 
$delete_url  = sprintf('%s/delete/get', $route);
$route = sprintf('%s/view/get', $route); 
$keys = $display_fields; 
?>
<h1>
    <?php echo $this->escapeHtml(ucfirst($title)); ?>
</h1>
<?php if ($msg != '') { ?>
<div class="alert alert-success">
    <?php echo $msg;?>
</div>
<?php } ?>
<?php if ($add) { ?>
<p>
    <a class="btn btn-success" href="
        <?php echo $this->url($route);?>">
        <i class="glyphicon glyphicon-plus"></i>Add new
    </a>
</p>
<?php } ?>

<div class="table-responsive">
<?php
if(isset($this->form)){
$form = $this->form;
$form->setAttribute('action', $this->serverUrl(true));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
?>
 <table class="table table-striped table-bordered model-list">
        <tbody>
        <tr>
        <?php 
            if($form->has('csrf_token')){
                $e=$form->get('csrf_token'); 
                echo $this->formInput($e);               
            }
            foreach ($form as $element) {
            $attributes=$element->getAttributes();
            $label = $element->getLabel();
            $type=$attributes['type'];
            $name=$attributes['name']; 
            if($label!=''){
                echo "<td>";
                echo $label;
                echo "</td>";    
            }
            if($type!='hidden'){
                echo "<td>";
                switch($type){
                case 'text':
                    echo $this->FormInput($element);
                    break;
                case 'select':
                    echo $this->FormSelect($element);
                    break;
                case 'multi_checkbox':
                    echo $this->FormMultiCheckbox($element);
                    break;
                case 'email':
                    echo $this->FormEmail($element);
                    break;
                case 'password':
                    echo $this->FormPassword($element);
                    break;
                case 'checkbox':
                    echo $this->FormCheckbox($element);
                    break;
                case 'textarea':
                    echo $this->formTextArea($element);
                    break;
                case 'submit':
                    echo $this->formSubmit($element);
                    break;
                }
                echo "</td>";    
            }
            
        } ?>
        </tr>
        </tbody>
    </table>
    <?php } ?>
    <table class="table table-striped table-bordered table-hover table-condensed">
        <tr>
            <?php foreach ($keys as $key) { ?>
            <td>
                <?php echo ucfirst($key);?>
            </td>
            <?php } ?>
            <td></td>
        </tr>
        <?php foreach ($paginator as $page) { echo " 
        <tr>"; foreach ($keys as $key) { echo " 
            <td>" . $page->{$key} . '</td>'; } ?>
            <td>
                <?=
                $this->partial((isset($buttons_partial) ? $buttons_partial : 'admin/base/templates/buttons'), array(
                    'perm'  => $perm,
                    'perms' => $perms,
                    'route' => $route,
                    'page'  => $page,
                ));
                ?>
            </td>
            <?php } ?>
        </table>
        <script src="
            <?php echo $this->basePath() . '/cms/js/bootstrap-confirm.js'; ?>">
        </script>
        <?php $route = explode('/', $route); $route = $route[0].'/'.$route[1]; 
        $array = array('route'=>$route);
        if(isset($params)){
            $array['params'] = $params;
        }
        echo $this->paginationControl($this->paginator, 'sliding', 
                array('admin/layout/slidePaginator.phtml','Users'), $array ); ?>
    </div>
    <?php echo $this->partial('admin/layout/footer.phtml');?>