<?php 
echo $this->partial('admin/layout/header.phtml'); 
$this->headTitle($title); 

$can_add     = (in_array(sprintf("%s-add", $perm), $perms) ? true : false);
$can_delete  = (in_array(sprintf("%s-delete", $perm), $perms) ? true : false);
$can_edit    = (in_array(sprintf("%s-edit", $perm), $perms) ? true : false);
$delete_url  = sprintf('%s/delete/get', $route);
$add_route   = sprintf('%s/add', $route);
?>

<h1><?= $this->escapeHtml(ucfirst($title)); ?></h1>

<?php if ($flash != '') { ?>
<div class="alert alert-success">
    <?= $flash; ?>
</div>
<?php } ?>

<?php if($can_add) { ?>
<p><a class="btn btn-success" href="<?= $this->url($add_route); ?>"><i class="glyphicon glyphicon-plus"></i>Add new</a></p>
<?php } ?>

<div class="table-responsive">
<?php
// TODO: Make this work
if(isset($this->form)) {
    $form = $this->form;
    $form->setAttribute('action', $this->serverUrl(true));
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
    echo $this->form()->openTag($form);
?>
 <table class="table table-striped table-bordered model-list">
    <tbody>
    <tr>
    <?php 
        if($form->has('csrf_token')){
            $e=$form->get('csrf_token'); 
            echo $this->formInput($e);               
        }
        foreach ($form as $element) {
        $attributes=$element->getAttributes();
        $label = $element->getLabel();
        $type=$attributes['type'];
        $name=$attributes['name']; 
        if($label!=''){
            echo "<td>";
            echo $label;
            echo "</td>";    
        }
        if($type!='hidden'){
            echo "<td>";
            switch($type){
            case 'text':
                echo $this->FormInput($element);
                break;
            case 'select':
                echo $this->FormSelect($element);
                break;
            case 'multi_checkbox':
                echo $this->FormMultiCheckbox($element);
                break;
            case 'email':
                echo $this->FormEmail($element);
                break;
            case 'password':
                echo $this->FormPassword($element);
                break;
            case 'checkbox':
                echo $this->FormCheckbox($element);
                break;
            case 'textarea':
                echo $this->formTextArea($element);
                break;
            case 'submit':
                echo $this->formSubmit($element);
                break;
            }
            echo "</td>";    
        }
        
    } ?>
    </tr>
    </tbody>
</table>
 <?php } ?>
 
<table class="table table-striped table-bordered table-hover table-condensed">
<tr>
    <?php foreach ($display_fields as $key) { ?>
    <td align="center"><b><?php
    if(isset($flr->elements[$key])) {
        echo $flr->elements[$key]['label'];
    }
    elseif($key == 'id') {
        echo "ID";
    }
    else {
        echo ucfirst($key);
    }
    ?></b></td>
    <?php } ?>
    <td></td>
</tr>

<?php foreach($records as $record) { ?>
<tr>
    <?php foreach($display_fields as $key) { ?>
    <td><?php
        if($key == 'id') {
            echo $record->id;
        }
        else {
            switch($flr->elements[$key]['type']) {
                case 'File':
                    if($record->has_file($key)) {
                        echo $record->files()->{$key}->filename;
                    }
                    break;
                
                default:
                    echo $record->{$key};
                    break;
            }
        }
    ?></td>
    <?php } ?>
    
    <td align="center"><?=
        $this->partial((isset($buttons_partial) ? $buttons_partial : 'admin/base/templates/buttonsplus'), array(
            'perm'   => $perm,
            'perms'  => $perms,
            'route'  => $route,
            'record' => $record,
            'page'   => $page,
        ));
    ?></td>
</tr>
<?php } ?>
</table>

<script src="
    <?php echo $this->basePath() . '/cms/js/bootstrap-confirm.js'; ?>">
</script>
<?php 
$array = array('route' => $route);

if(isset($params)){
    $array['params'] = $params;
}
echo $this->paginationControl($this->records, 'sliding', 
        array('admin/layout/slidePaginator.phtml','Users'), $array ); ?>
</div>
<?php echo $this->partial('admin/layout/footer.phtml');?>

