<?php echo $this->partial('admin/layout/header.phtml'); 
if(isset($plugings) && !is_null($plugings)) {
    if(in_array('fancybox', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/fancybox/jquery.fancybox.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/fancybox/jquery.fancybox.pack.js');    
    }
    if(in_array('colorpicker', $plugings)){
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/js/bootstrap-colorpicker/css/bootstrap-colorpicker.css');
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-colorpicker/js/bootstrap-colorpicker.js');    
    }
    if(in_array('datepicker',$plugings)){
        $this->headScript()->prependFile($this->basePath() . '/cms/js/bootstrap-datepicker.js');
        $this->headLink()->prependStylesheet($this->basePath() . '/cms/css/datepicker.css');
    }
}

if($has_ubigeo) {
    $ubigeo_form_extras = 'data-source-provinces="/provincias" data-source-districts="/distritos"';
    
?>
<script>
  function loadProv() {
    var $this = $(this),
      selectedVal = $this.val(),
      $el = $('#province'),
      $sub_el = $('#district'),
      html = '<option value="">Selecciona</option>', item;

    if (selectedVal === '') {
      $el.html(html)
         .attr('disabled');

      $el.parent()
         .addClass('is-disabled');
    } else {

      $el.html(html);
      $el.removeAttr('disabled');
      $el.parent().removeClass('is-disabled');
      $el.trigger('change');
      $sub_el.html(html).attr('disabled', 'disabled');
      $sub_el.parent().addClass('is-disabled');
      $sub_el.trigger('change');

      $.post($('form').attr('data-source-provinces'), {
        'cod_dpto': selectedVal
      }).done(function(data) {
        for (item in data) {
          html += '<option value="' + data[item].id + '">' + data[item].name + '</option>';
        }
        $el.html(html);
      });
    }
  };

  function loadDist() {
    var $el = $('#district'),
      $dept = $('#department'),
      $this = $(this),
      html = '<option value="">Selecciona</option>',
      selectedVal = $this.val(),
      item;

    if (selectedVal === '') {
      $el.html(html);
      $el.attr('disabled', 'disabled');
      $el.parent().addClass('is-disabled');
      $el.trigger('change');
    } else {
      $el.removeAttr('disabled');
      $el.parent().removeClass('is-disabled');
      $el.trigger('change');
      $.post($('form').attr('data-source-districts'), {
        'cod_prov': $this.val(),
        'cod_dpto': $dept.val(),
      }).done(function(data) {
        for (item in data) {
          html += '<option value="' + data[item].id + '">' + data[item].name + '</option>';
        }
        $el.html(html);
      });
    }
  };

  function setupRegisterForm() {
    var dpt = $('#department'),
      prov = $('#province'),
      dist = $('#district');   

    if (prov.length > 0) {
      dpt.on('change', loadProv);
      prov.on('change', loadDist);
    }
  };

  $(document).on('ready', function(){
    setupRegisterForm();
  });
</script>
<?php
}
else {
    $ubigeo_form_extras = '';
}

if(isset($url)) {
?>
<div id="url" data-url=<?php echo $url; ?>></div>
    <script src="<?php echo $this->basePath() . '/cms/js/section.js'; ?>">
</script>
<?php
}
?>

<a class="btn btn-primary" href="<?php echo $this->url($route); ?>">Regresar</a>

<h1><?= $title ?></h1>

<?php
if(isset($errors) && count($errors) > 0) {
?>
<div class="alert alert-danger alert-error">
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <strong>Error!</strong> Se encontraron errores o campos que no se han llenado
</div>
<?php
}
?>

<form method="POST" action="<?= $this->serverUrl(true) ?>" class="form-horizontal" <?= $ubigeo_form_extras ?>>

<?php
$e = $form->get('csrf');
echo $this->formInput($e);
?>

<input type="hidden" name="id" value="<?= ($this->id === NULL ? '0' : $this->id) ?>">

<?php
if(isset($tabs) && !is_null($tabs)) {
    $keys = array_keys($tabs);
?>
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <?php
        $index  = 0;
        $active = '';
        foreach($keys as $tab) {
            $active = ($index == 0 ? 'active' : '');
            $index++;
        ?>
            <li class="<?= $active; ?>"><a href="#<?= $tab; ?>" data-toggle="tab"><?= $tab; ?></a></li>
        <?php
        }
        ?>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php
        $index = 0;
        $active= '';
        foreach($tabs as $key => $tab) {
            $active = ($index == 0 ? 'active' : '');
            $index++;
        ?>
            <div class="tab-pane <?= $active; ?>" id="<?= $key ?>">
                <table class="table table-striped table-bordered model-list">
                    <tbody>
                    <?php
                    foreach($tab as $t) {
                        $element = $form->get($t);
                        $vars = array("element"=>$element,'files'=>$files);
                        if(isset($object->file_path)) {
                            $vars['object'] = $object->file_path;
                        }
                        echo $this->partial('admin/base/templates/printForm.phtml', $vars);
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        <?php
        }
        ?>
    </div>
<?php
}
else {
    ?>
    <table class="table table-striped table-bordered model-list">
    <tbody>
    <?php
    foreach($flr->elements as $name => $element) {
        if($name !== 'csrf') {
            $vars = array(
                'name'         => $name,
                'flr'          => $flr,
                'form_element' => $form->get($name),
                'record'       => $record,
            );
            
            echo $this->partial('admin/base/templates/printForm.phtml', $vars);
        }
    }
    ?>
    </tbody></table>
<?php
}

?>

<input type="submit" value="Save">
</form>

<?php echo $this->partial('admin/layout/footer.phtml');?>

